# Generated by Django 3.1 on 2020-08-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=42)),
                ('contact_address', models.CharField(max_length=42)),
                ('contact_name', models.CharField(max_length=128)),
                ('combined_address', models.CharField(max_length=84, unique=True)),
            ],
            options={
                'verbose_name': 'Contacts',
                'verbose_name_plural': 'Contacts',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('txHash', models.CharField(max_length=66, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=42)),
                ('date_of_transaction', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
