# Generated by Django 3.1 on 2020-08-21 17:22

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={},
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact_address',
            field=models.CharField(max_length=42, validators=[api.validators.ethAddress]),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='owner',
            field=models.CharField(max_length=42, validators=[api.validators.ethAddress]),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='txHash',
            field=models.CharField(max_length=66, primary_key=True, serialize=False, validators=[api.validators.txHash]),
        ),
        migrations.AlterModelTable(
            name='contacts',
            table=None,
        ),
    ]
